language:
  - go

branchs:
  only:
    - master
env:
  - GO111MODULE=on


before_install:


install:
  - go mod tidy

before_script:


scrip:

after_success:

  - before_deploy:
      - go build main.go


  - deploy:
      provider: releases
      api_key:
        secure:"$API_KEY"

        file: "main"
        skip_cleanup: true
        on:
          tags: true
          repo: edte/ci-test

  - after_deploy:

  - after_script:

after_failure:






#before_install:
#  - openssl aes-256-cbc -K $encrypted_3d82dee1fe6a_key -iv $encrypted_3d82dee1fe6a_iv -in id_rsa.enc -out ~/
#  .ssh/id_rsa -d
#
#  touch ssh_config
#  echo Host test >> ssh_config
#  echo HostName 47.98.57.152  >> ssh_config
#  echo User root  >> ssh_config
#  echo IdentitiesOnly yes  >> ssh_config
#  echo IdentityFile ~/.ssh/id_rsa  >> ssh_config
#
#  chmod 600 ssh_config
#  chmod 600 ~/.ssh/id_rsa

#after_success:
#  ssh test
#  touch a


# - go mod tidy
#- go build main.go

