language:
  - go

branchs:
  only:
    - master

script:
  - go mod tidy
  - go build main.go

before_install:
  - openssl aes-256-cbc -K $encrypted_3d82dee1fe6a_key -iv $encrypted_3d82dee1fe6a_iv -in id_rsa.enc -out ~/
  .ssh/id_rsa -d


    